- hosts: servers
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: linux-dotfiles.zip
        dest: /usr/src/storage/linux-dotfiles.zip
        owner: deploy
        group: deploy
        mode: '0644'
