version: "3.1"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "9000"
    ports:
      - "9000:9000"

volumes:
  portainer_data:
    driver: local
