name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set SSH key
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.HOST }}

      - name: Generate zip file
        run: |
          git archive --format tar --output linux-dotfiles.tgz main

      - name: Play Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/sync.yml
